// Autogenerated from Pigeon (v29.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "control_probe_api.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <cmath>
#include <limits>
#include <map>
#include <optional>
#include <sstream>
#include <string>

namespace mystia_control_probe {
using ::flutter::BasicMessageChannel;
using ::flutter::CustomEncodableValue;
using ::flutter::EncodableList;
using ::flutter::EncodableMap;
using ::flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

namespace {
template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b);

bool PigeonInternalDeepEquals(const double& a, const double& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b);

template<typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b);

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b);

template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b) {
  return a == b;
}

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (size_t i = 0; i < a.size(); ++i) {
    if (!PigeonInternalDeepEquals(a[i], b[i])) {
      return false;
    }
  }
  return true;
}

template <typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (const auto& kv : a) {
    bool found = false;
    for (const auto& b_kv : b) {
      if (PigeonInternalDeepEquals(kv.first, b_kv.first)) {
        if (PigeonInternalDeepEquals(kv.second, b_kv.second)) {
          found = true;
          break;
        } else {
          return false;
        }
      }
    }
    if (!found) {
      return false;
    }
  }
  return true;
}

bool PigeonInternalDeepEquals(const double& a, const double& b) {
  // Normalize -0.0 to 0.0 and handle NaN equality.
  return (a == b) || (std::isnan(a) && std::isnan(b));
}

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b) {
  if (!a && !b) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b) {
  if (a.get() == b.get()) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b) {
  if (a.index() != b.index()) {
    return false;
  }
  if (const double* da = std::get_if<double>(&a)) {
    return PigeonInternalDeepEquals(*da, std::get<double>(b));
  } else if (const ::flutter::EncodableList* la = std::get_if<::flutter::EncodableList>(&a)) {
    return PigeonInternalDeepEquals(*la, std::get<::flutter::EncodableList>(b));
  } else if (const ::flutter::EncodableMap* ma = std::get_if<::flutter::EncodableMap>(&a)) {
    return PigeonInternalDeepEquals(*ma, std::get<::flutter::EncodableMap>(b));
  }
  return a == b;
}

template <typename T>
size_t PigeonInternalDeepHash(const T& v);

size_t PigeonInternalDeepHash(const double& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v);

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v);

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v);

template <typename T>
size_t PigeonInternalDeepHash(const T& v) {
  return std::hash<T>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v) {
  size_t result = 1;
  for (const auto& item : v) {
    result = result * 31 + PigeonInternalDeepHash(item);
  }
  return result;
}

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v) {
  size_t result = 0;
  for (const auto& kv : v) {
    result += ((PigeonInternalDeepHash(kv.first) * 31) ^ PigeonInternalDeepHash(kv.second));
  }
  return result;
}

size_t PigeonInternalDeepHash(const double& v) {
  if (std::isnan(v)) {
    // Normalize NaN to a consistent hash.
    return std::hash<double>()(std::numeric_limits<double>::quiet_NaN());
  }
  if (v == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return std::hash<double>()(0.0);
  }
  return std::hash<double>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v) {
  size_t result = v.index();
  if (const double* dv = std::get_if<double>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*dv);
  } else if (const ::flutter::EncodableList* lv =
                 std::get_if<::flutter::EncodableList>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*lv);
  } else if (const ::flutter::EncodableMap* mv =
                 std::get_if<::flutter::EncodableMap>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*mv);
  } else {
    std::visit(
        [&result](const auto& val) {
          using T = std::decay_t<decltype(val)>;
          if constexpr (!std::is_same_v<T, double> &&
                        !std::is_same_v<T, ::flutter::EncodableList> &&
                        !std::is_same_v<T, ::flutter::EncodableMap> &&
                        !std::is_same_v<T, std::monostate> &&
                        !std::is_same_v<T, ::flutter::CustomEncodableValue>) {
            result = result * 31 + PigeonInternalDeepHash(val);
          }
        },
        v);
  }
  return result;
}

template <typename T>
std::string PigeonInternalToString(const T& v);

std::string PigeonInternalToString(const bool& v);

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v);

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v);

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v);

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v);

std::string PigeonInternalToString(const ::flutter::EncodableValue& v);

template <typename T>
std::string PigeonInternalToString(const T& v) {
  std::stringstream ss;
  if constexpr (std::is_enum_v<T>) {
    ss << static_cast<int>(v);
  } else {
    ss << v;
  }
  return ss.str();
}

std::string PigeonInternalToString(const bool& v) {
  return v ? "true" : "false";
}

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v) {
  std::stringstream ss;
  ss << "[";
  for (size_t i = 0; i < v.size(); ++i) {
    if (i > 0) {
      ss << ", ";
    }
    ss << PigeonInternalToString(v[i]);
  }
  ss << "]";
  return ss.str();
}

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v) {
  std::stringstream ss;
  ss << "{";
  bool first = true;
  for (const auto& kv : v) {
    if (!first) {
      ss << ", ";
    }
    first = false;
    ss << PigeonInternalToString(kv.first) << ": " << PigeonInternalToString(kv.second);
  }
  ss << "}";
  return ss.str();
}

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

std::string PigeonInternalToString(const ::flutter::EncodableValue& v) {
  return std::visit(
      [](const auto& val) {
        using T = std::decay_t<decltype(val)>;
        if constexpr (std::is_same_v<T, std::monostate>) {
          return std::string("null");
        } else if constexpr (std::is_same_v<T, bool>) {
          return val ? std::string("true") : std::string("false");
        } else if constexpr (std::is_same_v<T, std::string>) {
          return "\"" + val + "\"";
        } else if constexpr (std::is_same_v<T, ::flutter::CustomEncodableValue>) {
          return std::string("[custom]");
        } else {
          return PigeonInternalToString(val);
        }
      },
      v);
}

}  // namespace
// ControlCommand

ControlCommand::ControlCommand(
  const ControlOperation& operation,
  int64_t request_id,
  bool flutter_focused,
  int64_t dart_f8_down_count)
 : operation_(operation),
    request_id_(request_id),
    flutter_focused_(flutter_focused),
    dart_f8_down_count_(dart_f8_down_count) {}

const ControlOperation& ControlCommand::operation() const {
  return operation_;
}

void ControlCommand::set_operation(const ControlOperation& value_arg) {
  operation_ = value_arg;
}


int64_t ControlCommand::request_id() const {
  return request_id_;
}

void ControlCommand::set_request_id(int64_t value_arg) {
  request_id_ = value_arg;
}


bool ControlCommand::flutter_focused() const {
  return flutter_focused_;
}

void ControlCommand::set_flutter_focused(bool value_arg) {
  flutter_focused_ = value_arg;
}


int64_t ControlCommand::dart_f8_down_count() const {
  return dart_f8_down_count_;
}

void ControlCommand::set_dart_f8_down_count(int64_t value_arg) {
  dart_f8_down_count_ = value_arg;
}


EncodableList ControlCommand::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(CustomEncodableValue(operation_));
  list.push_back(EncodableValue(request_id_));
  list.push_back(EncodableValue(flutter_focused_));
  list.push_back(EncodableValue(dart_f8_down_count_));
  return list;
}

ControlCommand ControlCommand::FromEncodableList(const EncodableList& list) {
  ControlCommand decoded(
    std::any_cast<const ControlOperation&>(std::get<CustomEncodableValue>(list[0])),
    std::get<int64_t>(list[1]),
    std::get<bool>(list[2]),
    std::get<int64_t>(list[3]));
  return decoded;
}

bool ControlCommand::operator==(const ControlCommand& other) const {
  return PigeonInternalDeepEquals(operation_, other.operation_) && PigeonInternalDeepEquals(request_id_, other.request_id_) && PigeonInternalDeepEquals(flutter_focused_, other.flutter_focused_) && PigeonInternalDeepEquals(dart_f8_down_count_, other.dart_f8_down_count_);
}

bool ControlCommand::operator!=(const ControlCommand& other) const {
  return !(*this == other);
}

size_t ControlCommand::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(operation_);
  result = result * 31 + PigeonInternalDeepHash(request_id_);
  result = result * 31 + PigeonInternalDeepHash(flutter_focused_);
  result = result * 31 + PigeonInternalDeepHash(dart_f8_down_count_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const ControlCommand& obj) {
  os << "ControlCommand(";
  os << "operation: ";
  os << PigeonInternalToString(obj.operation_);
  os << ", request_id: ";
  os << PigeonInternalToString(obj.request_id_);
  os << ", flutter_focused: ";
  os << PigeonInternalToString(obj.flutter_focused_);
  os << ", dart_f8_down_count: ";
  os << PigeonInternalToString(obj.dart_f8_down_count_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const ControlCommand& v) {
  return v.Hash();
}

// ControlSnapshot

ControlSnapshot::ControlSnapshot(
  const std::string& git_sha,
  int64_t process_id,
  int64_t sequence,
  const std::string& evidence_json)
 : git_sha_(git_sha),
    process_id_(process_id),
    sequence_(sequence),
    evidence_json_(evidence_json) {}

const std::string& ControlSnapshot::git_sha() const {
  return git_sha_;
}

void ControlSnapshot::set_git_sha(std::string_view value_arg) {
  git_sha_ = value_arg;
}


int64_t ControlSnapshot::process_id() const {
  return process_id_;
}

void ControlSnapshot::set_process_id(int64_t value_arg) {
  process_id_ = value_arg;
}


int64_t ControlSnapshot::sequence() const {
  return sequence_;
}

void ControlSnapshot::set_sequence(int64_t value_arg) {
  sequence_ = value_arg;
}


const std::string& ControlSnapshot::evidence_json() const {
  return evidence_json_;
}

void ControlSnapshot::set_evidence_json(std::string_view value_arg) {
  evidence_json_ = value_arg;
}


EncodableList ControlSnapshot::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(EncodableValue(git_sha_));
  list.push_back(EncodableValue(process_id_));
  list.push_back(EncodableValue(sequence_));
  list.push_back(EncodableValue(evidence_json_));
  return list;
}

ControlSnapshot ControlSnapshot::FromEncodableList(const EncodableList& list) {
  ControlSnapshot decoded(
    std::get<std::string>(list[0]),
    std::get<int64_t>(list[1]),
    std::get<int64_t>(list[2]),
    std::get<std::string>(list[3]));
  return decoded;
}

bool ControlSnapshot::operator==(const ControlSnapshot& other) const {
  return PigeonInternalDeepEquals(git_sha_, other.git_sha_) && PigeonInternalDeepEquals(process_id_, other.process_id_) && PigeonInternalDeepEquals(sequence_, other.sequence_) && PigeonInternalDeepEquals(evidence_json_, other.evidence_json_);
}

bool ControlSnapshot::operator!=(const ControlSnapshot& other) const {
  return !(*this == other);
}

size_t ControlSnapshot::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(git_sha_);
  result = result * 31 + PigeonInternalDeepHash(process_id_);
  result = result * 31 + PigeonInternalDeepHash(sequence_);
  result = result * 31 + PigeonInternalDeepHash(evidence_json_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const ControlSnapshot& obj) {
  os << "ControlSnapshot(";
  os << "git_sha: ";
  os << PigeonInternalToString(obj.git_sha_);
  os << ", process_id: ";
  os << PigeonInternalToString(obj.process_id_);
  os << ", sequence: ";
  os << PigeonInternalToString(obj.sequence_);
  os << ", evidence_json: ";
  os << PigeonInternalToString(obj.evidence_json_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const ControlSnapshot& v) {
  return v.Hash();
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  ::flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<ControlOperation>(enum_arg_value));
      }
    case 130: {
        return CustomEncodableValue(ControlCommand::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 131: {
        return CustomEncodableValue(ControlSnapshot::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return ::flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  ::flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(ControlOperation)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<ControlOperation>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(ControlCommand)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(std::any_cast<ControlCommand>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(ControlSnapshot)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<ControlSnapshot>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  ::flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by ControlProbeHostApi.
const ::flutter::StandardMessageCodec& ControlProbeHostApi::GetCodec() {
  return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `ControlProbeHostApi` to handle messages through the `binary_messenger`.
void ControlProbeHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  ControlProbeHostApi* api) {
  ControlProbeHostApi::SetUp(binary_messenger, api, "");
}

void ControlProbeHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  ControlProbeHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.mystia_steward_companion_window_probe.ControlProbeHostApi.execute" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_command_arg = args.at(0);
          if (encodable_command_arg.IsNull()) {
            reply(WrapError("command_arg unexpectedly null."));
            return;
          }
          const auto& command_arg = std::any_cast<const ControlCommand&>(std::get<CustomEncodableValue>(encodable_command_arg));
          api->Execute(command_arg, [reply](ErrorOr<ControlSnapshot>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.mystia_steward_companion_window_probe.ControlProbeHostApi.finish" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_report_json_arg = args.at(0);
          if (encodable_report_json_arg.IsNull()) {
            reply(WrapError("report_json_arg unexpectedly null."));
            return;
          }
          const auto& report_json_arg = std::get<std::string>(encodable_report_json_arg);
          const auto& encodable_exit_code_arg = args.at(1);
          if (encodable_exit_code_arg.IsNull()) {
            reply(WrapError("exit_code_arg unexpectedly null."));
            return;
          }
          const int64_t exit_code_arg = encodable_exit_code_arg.LongValue();
          api->Finish(report_json_arg, exit_code_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue ControlProbeHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue ControlProbeHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace mystia_control_probe
