// Autogenerated from Pigeon (v29.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_CONTROL_PROBE_API_G_H_
#define PIGEON_CONTROL_PROBE_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <ostream>
#include <string>

namespace mystia_control_probe {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class ControlProbeHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class ControlOperation {
  kInitialize = 0,
  kInspect = 1,
  kFocusGame = 2,
  kReturnGame = 3,
  kHideProbe = 4,
  kSetPassThrough = 5,
  kSetInteractive = 6,
  kPressF8 = 7,
  kReleaseF8 = 8,
  kClickProbe = 9,
  kSendFocusKey = 10,
  kCloseGame = 11
};


// Generated class from Pigeon that represents data sent in messages.
class ControlCommand {
 public:
  // Constructs an object setting all fields.
  explicit ControlCommand(
    const ControlOperation& operation,
    int64_t request_id,
    bool flutter_focused,
    int64_t dart_f8_down_count);

  const ControlOperation& operation() const;
  void set_operation(const ControlOperation& value_arg);

  int64_t request_id() const;
  void set_request_id(int64_t value_arg);

  bool flutter_focused() const;
  void set_flutter_focused(bool value_arg);

  int64_t dart_f8_down_count() const;
  void set_dart_f8_down_count(int64_t value_arg);

  bool operator==(const ControlCommand& other) const;
  bool operator!=(const ControlCommand& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const ControlCommand& obj);
 private:
  static ControlCommand FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class ControlProbeHostApi;
  friend class PigeonInternalCodecSerializer;
  ControlOperation operation_;
  int64_t request_id_;
  bool flutter_focused_;
  int64_t dart_f8_down_count_;
};


// Generated class from Pigeon that represents data sent in messages.
class ControlSnapshot {
 public:
  // Constructs an object setting all fields.
  explicit ControlSnapshot(
    const std::string& git_sha,
    int64_t process_id,
    int64_t sequence,
    const std::string& evidence_json);

  const std::string& git_sha() const;
  void set_git_sha(std::string_view value_arg);

  int64_t process_id() const;
  void set_process_id(int64_t value_arg);

  int64_t sequence() const;
  void set_sequence(int64_t value_arg);

  const std::string& evidence_json() const;
  void set_evidence_json(std::string_view value_arg);

  bool operator==(const ControlSnapshot& other) const;
  bool operator!=(const ControlSnapshot& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const ControlSnapshot& obj);
 private:
  static ControlSnapshot FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class ControlProbeHostApi;
  friend class PigeonInternalCodecSerializer;
  std::string git_sha_;
  int64_t process_id_;
  int64_t sequence_;
  std::string evidence_json_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class ControlProbeHostApi {
 public:
  ControlProbeHostApi(const ControlProbeHostApi&) = delete;
  ControlProbeHostApi& operator=(const ControlProbeHostApi&) = delete;
  virtual ~ControlProbeHostApi() {}
  virtual void Execute(
    const ControlCommand& command,
    std::function<void(ErrorOr<ControlSnapshot> reply)> result) = 0;
  virtual void Finish(
    const std::string& report_json,
    int64_t exit_code,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;

  // The codec used by ControlProbeHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `ControlProbeHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    ControlProbeHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    ControlProbeHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  ControlProbeHostApi() = default;
};
}  // namespace mystia_control_probe
#endif  // PIGEON_CONTROL_PROBE_API_G_H_
