// Autogenerated from Pigeon (v29.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_INPUT_PROBE_API_G_H_
#define PIGEON_INPUT_PROBE_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <ostream>
#include <string>

namespace mystia_input_probe {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class InputProbeHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class InputProbeMode {
  kInteractive = 0,
  kPassThrough = 1
};

enum class FocusOperation {
  kInitialize = 0,
  kInspect = 1,
  kFocusGame = 2,
  kFocusProbe = 3,
  kSetPassThrough = 4,
  kHideProbe = 5,
  kClickProbe = 6,
  kSendFocusKey = 7,
  kCloseGame = 8
};


// Generated class from Pigeon that represents data sent in messages.
class XInputState {
 public:
  // Constructs an object setting all fields.
  explicit XInputState(
    int64_t packet_number,
    int64_t buttons,
    int64_t left_trigger,
    int64_t right_trigger,
    int64_t thumb_l_x,
    int64_t thumb_l_y,
    int64_t thumb_r_x,
    int64_t thumb_r_y);

  int64_t packet_number() const;
  void set_packet_number(int64_t value_arg);

  int64_t buttons() const;
  void set_buttons(int64_t value_arg);

  int64_t left_trigger() const;
  void set_left_trigger(int64_t value_arg);

  int64_t right_trigger() const;
  void set_right_trigger(int64_t value_arg);

  int64_t thumb_l_x() const;
  void set_thumb_l_x(int64_t value_arg);

  int64_t thumb_l_y() const;
  void set_thumb_l_y(int64_t value_arg);

  int64_t thumb_r_x() const;
  void set_thumb_r_x(int64_t value_arg);

  int64_t thumb_r_y() const;
  void set_thumb_r_y(int64_t value_arg);

  bool operator==(const XInputState& other) const;
  bool operator!=(const XInputState& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const XInputState& obj);
 private:
  static XInputState FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class XInputSlot;
  friend class InputProbeHostApi;
  friend class PigeonInternalCodecSerializer;
  int64_t packet_number_;
  int64_t buttons_;
  int64_t left_trigger_;
  int64_t right_trigger_;
  int64_t thumb_l_x_;
  int64_t thumb_l_y_;
  int64_t thumb_r_x_;
  int64_t thumb_r_y_;
};


// Generated class from Pigeon that represents data sent in messages.
class XInputSlot {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit XInputSlot(
    int64_t index,
    int64_t result_code);

  // Constructs an object setting all fields.
  explicit XInputSlot(
    int64_t index,
    int64_t result_code,
    const XInputState* state);

  ~XInputSlot() = default;
  XInputSlot(const XInputSlot& other);
  XInputSlot& operator=(const XInputSlot& other);
  XInputSlot(XInputSlot&& other) = default;
  XInputSlot& operator=(XInputSlot&& other) noexcept = default;
  int64_t index() const;
  void set_index(int64_t value_arg);

  int64_t result_code() const;
  void set_result_code(int64_t value_arg);

  const XInputState* state() const;
  void set_state(const XInputState* value_arg);
  void set_state(const XInputState& value_arg);

  bool operator==(const XInputSlot& other) const;
  bool operator!=(const XInputSlot& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const XInputSlot& obj);
 private:
  static XInputSlot FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class InputProbeHostApi;
  friend class PigeonInternalCodecSerializer;
  int64_t index_;
  int64_t result_code_;
  std::unique_ptr<XInputState> state_;
};


// Generated class from Pigeon that represents data sent in messages.
class XInputSnapshot {
 public:
  // Constructs an object setting all fields.
  explicit XInputSnapshot(
    const std::string& native_git_sha,
    int64_t process_id,
    int64_t sequence,
    int64_t monotonic_micros,
    const std::string& system_dll_path,
    int64_t foreground_process_id,
    bool probe_focused,
    const ::flutter::EncodableList& slots);

  const std::string& native_git_sha() const;
  void set_native_git_sha(std::string_view value_arg);

  int64_t process_id() const;
  void set_process_id(int64_t value_arg);

  int64_t sequence() const;
  void set_sequence(int64_t value_arg);

  int64_t monotonic_micros() const;
  void set_monotonic_micros(int64_t value_arg);

  const std::string& system_dll_path() const;
  void set_system_dll_path(std::string_view value_arg);

  int64_t foreground_process_id() const;
  void set_foreground_process_id(int64_t value_arg);

  bool probe_focused() const;
  void set_probe_focused(bool value_arg);

  const ::flutter::EncodableList& slots() const;
  void set_slots(const ::flutter::EncodableList& value_arg);

  bool operator==(const XInputSnapshot& other) const;
  bool operator!=(const XInputSnapshot& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const XInputSnapshot& obj);
 private:
  static XInputSnapshot FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class InputProbeHostApi;
  friend class PigeonInternalCodecSerializer;
  std::string native_git_sha_;
  int64_t process_id_;
  int64_t sequence_;
  int64_t monotonic_micros_;
  std::string system_dll_path_;
  int64_t foreground_process_id_;
  bool probe_focused_;
  ::flutter::EncodableList slots_;
};


// Generated class from Pigeon that represents data sent in messages.
class FocusCommand {
 public:
  // Constructs an object setting all fields.
  explicit FocusCommand(
    const FocusOperation& operation,
    int64_t request_id);

  const FocusOperation& operation() const;
  void set_operation(const FocusOperation& value_arg);

  int64_t request_id() const;
  void set_request_id(int64_t value_arg);

  bool operator==(const FocusCommand& other) const;
  bool operator!=(const FocusCommand& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const FocusCommand& obj);
 private:
  static FocusCommand FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class InputProbeHostApi;
  friend class PigeonInternalCodecSerializer;
  FocusOperation operation_;
  int64_t request_id_;
};


// Generated class from Pigeon that represents data sent in messages.
class ForegroundGrantSnapshot {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit ForegroundGrantSnapshot(
    bool ready,
    bool identity_matched,
    int64_t grant_sequence,
    int64_t request_id,
    int64_t response_sequence,
    int64_t issuer_process_id,
    int64_t target_process_id,
    int64_t foreground_hwnd,
    int64_t foreground_process_id,
    int64_t foreground_after_hwnd,
    int64_t foreground_after_process_id,
    bool activation_requested);

  // Constructs an object setting all fields.
  explicit ForegroundGrantSnapshot(
    bool ready,
    bool identity_matched,
    int64_t grant_sequence,
    int64_t request_id,
    int64_t response_sequence,
    int64_t issuer_process_id,
    int64_t target_process_id,
    const bool* allow_result,
    const int64_t* allow_error,
    int64_t foreground_hwnd,
    int64_t foreground_process_id,
    int64_t foreground_after_hwnd,
    int64_t foreground_after_process_id,
    bool activation_requested);

  bool ready() const;
  void set_ready(bool value_arg);

  bool identity_matched() const;
  void set_identity_matched(bool value_arg);

  int64_t grant_sequence() const;
  void set_grant_sequence(int64_t value_arg);

  int64_t request_id() const;
  void set_request_id(int64_t value_arg);

  int64_t response_sequence() const;
  void set_response_sequence(int64_t value_arg);

  int64_t issuer_process_id() const;
  void set_issuer_process_id(int64_t value_arg);

  int64_t target_process_id() const;
  void set_target_process_id(int64_t value_arg);

  const bool* allow_result() const;
  void set_allow_result(const bool* value_arg);
  void set_allow_result(bool value_arg);

  const int64_t* allow_error() const;
  void set_allow_error(const int64_t* value_arg);
  void set_allow_error(int64_t value_arg);

  int64_t foreground_hwnd() const;
  void set_foreground_hwnd(int64_t value_arg);

  int64_t foreground_process_id() const;
  void set_foreground_process_id(int64_t value_arg);

  int64_t foreground_after_hwnd() const;
  void set_foreground_after_hwnd(int64_t value_arg);

  int64_t foreground_after_process_id() const;
  void set_foreground_after_process_id(int64_t value_arg);

  bool activation_requested() const;
  void set_activation_requested(bool value_arg);

  bool operator==(const ForegroundGrantSnapshot& other) const;
  bool operator!=(const ForegroundGrantSnapshot& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const ForegroundGrantSnapshot& obj);
 private:
  static ForegroundGrantSnapshot FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class FocusSnapshot;
  friend class InputProbeHostApi;
  friend class PigeonInternalCodecSerializer;
  bool ready_;
  bool identity_matched_;
  int64_t grant_sequence_;
  int64_t request_id_;
  int64_t response_sequence_;
  int64_t issuer_process_id_;
  int64_t target_process_id_;
  std::optional<bool> allow_result_;
  std::optional<int64_t> allow_error_;
  int64_t foreground_hwnd_;
  int64_t foreground_process_id_;
  int64_t foreground_after_hwnd_;
  int64_t foreground_after_process_id_;
  bool activation_requested_;
};


// Generated class from Pigeon that represents data sent in messages.
class FocusSnapshot {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit FocusSnapshot(
    const std::string& native_git_sha,
    int64_t process_id,
    int64_t sequence,
    int64_t request_id,
    bool request_pending,
    int64_t game_pid,
    const std::string& game_creation_time_hex,
    bool game_alive,
    bool game_identity_matched,
    bool game_close_requested,
    int64_t game_window_count,
    int64_t game_thread_id,
    int64_t probe_hwnd,
    int64_t probe_child_hwnd,
    int64_t probe_thread_id,
    bool probe_visible,
    const InputProbeMode& input_mode,
    int64_t foreground_hwnd,
    int64_t foreground_process_id,
    int64_t focus_owner_pid,
    int64_t probe_mouse_down,
    int64_t probe_mouse_up,
    int64_t probe_key_down,
    bool last_foreground_result,
    int64_t last_foreground_error,
    const std::string& diagnostics_json);

  // Constructs an object setting all fields.
  explicit FocusSnapshot(
    const std::string& native_git_sha,
    int64_t process_id,
    int64_t sequence,
    int64_t request_id,
    bool request_pending,
    int64_t game_pid,
    const std::string& game_creation_time_hex,
    bool game_alive,
    bool game_identity_matched,
    const int64_t* game_exit_code,
    bool game_close_requested,
    const int64_t* game_hwnd,
    int64_t game_window_count,
    int64_t game_thread_id,
    const int64_t* game_focus_hwnd,
    int64_t probe_hwnd,
    int64_t probe_child_hwnd,
    int64_t probe_thread_id,
    bool probe_visible,
    const InputProbeMode& input_mode,
    int64_t foreground_hwnd,
    int64_t foreground_process_id,
    const int64_t* focus_hwnd,
    int64_t focus_owner_pid,
    int64_t probe_mouse_down,
    int64_t probe_mouse_up,
    int64_t probe_key_down,
    bool last_foreground_result,
    int64_t last_foreground_error,
    const ForegroundGrantSnapshot* foreground_grant,
    const std::string& diagnostics_json);

  ~FocusSnapshot() = default;
  FocusSnapshot(const FocusSnapshot& other);
  FocusSnapshot& operator=(const FocusSnapshot& other);
  FocusSnapshot(FocusSnapshot&& other) = default;
  FocusSnapshot& operator=(FocusSnapshot&& other) noexcept = default;
  const std::string& native_git_sha() const;
  void set_native_git_sha(std::string_view value_arg);

  int64_t process_id() const;
  void set_process_id(int64_t value_arg);

  int64_t sequence() const;
  void set_sequence(int64_t value_arg);

  int64_t request_id() const;
  void set_request_id(int64_t value_arg);

  bool request_pending() const;
  void set_request_pending(bool value_arg);

  int64_t game_pid() const;
  void set_game_pid(int64_t value_arg);

  const std::string& game_creation_time_hex() const;
  void set_game_creation_time_hex(std::string_view value_arg);

  bool game_alive() const;
  void set_game_alive(bool value_arg);

  bool game_identity_matched() const;
  void set_game_identity_matched(bool value_arg);

  const int64_t* game_exit_code() const;
  void set_game_exit_code(const int64_t* value_arg);
  void set_game_exit_code(int64_t value_arg);

  bool game_close_requested() const;
  void set_game_close_requested(bool value_arg);

  const int64_t* game_hwnd() const;
  void set_game_hwnd(const int64_t* value_arg);
  void set_game_hwnd(int64_t value_arg);

  int64_t game_window_count() const;
  void set_game_window_count(int64_t value_arg);

  int64_t game_thread_id() const;
  void set_game_thread_id(int64_t value_arg);

  const int64_t* game_focus_hwnd() const;
  void set_game_focus_hwnd(const int64_t* value_arg);
  void set_game_focus_hwnd(int64_t value_arg);

  int64_t probe_hwnd() const;
  void set_probe_hwnd(int64_t value_arg);

  int64_t probe_child_hwnd() const;
  void set_probe_child_hwnd(int64_t value_arg);

  int64_t probe_thread_id() const;
  void set_probe_thread_id(int64_t value_arg);

  bool probe_visible() const;
  void set_probe_visible(bool value_arg);

  const InputProbeMode& input_mode() const;
  void set_input_mode(const InputProbeMode& value_arg);

  int64_t foreground_hwnd() const;
  void set_foreground_hwnd(int64_t value_arg);

  int64_t foreground_process_id() const;
  void set_foreground_process_id(int64_t value_arg);

  const int64_t* focus_hwnd() const;
  void set_focus_hwnd(const int64_t* value_arg);
  void set_focus_hwnd(int64_t value_arg);

  int64_t focus_owner_pid() const;
  void set_focus_owner_pid(int64_t value_arg);

  int64_t probe_mouse_down() const;
  void set_probe_mouse_down(int64_t value_arg);

  int64_t probe_mouse_up() const;
  void set_probe_mouse_up(int64_t value_arg);

  int64_t probe_key_down() const;
  void set_probe_key_down(int64_t value_arg);

  bool last_foreground_result() const;
  void set_last_foreground_result(bool value_arg);

  int64_t last_foreground_error() const;
  void set_last_foreground_error(int64_t value_arg);

  const ForegroundGrantSnapshot* foreground_grant() const;
  void set_foreground_grant(const ForegroundGrantSnapshot* value_arg);
  void set_foreground_grant(const ForegroundGrantSnapshot& value_arg);

  const std::string& diagnostics_json() const;
  void set_diagnostics_json(std::string_view value_arg);

  bool operator==(const FocusSnapshot& other) const;
  bool operator!=(const FocusSnapshot& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const FocusSnapshot& obj);
 private:
  static FocusSnapshot FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class InputProbeHostApi;
  friend class PigeonInternalCodecSerializer;
  std::string native_git_sha_;
  int64_t process_id_;
  int64_t sequence_;
  int64_t request_id_;
  bool request_pending_;
  int64_t game_pid_;
  std::string game_creation_time_hex_;
  bool game_alive_;
  bool game_identity_matched_;
  std::optional<int64_t> game_exit_code_;
  bool game_close_requested_;
  std::optional<int64_t> game_hwnd_;
  int64_t game_window_count_;
  int64_t game_thread_id_;
  std::optional<int64_t> game_focus_hwnd_;
  int64_t probe_hwnd_;
  int64_t probe_child_hwnd_;
  int64_t probe_thread_id_;
  bool probe_visible_;
  InputProbeMode input_mode_;
  int64_t foreground_hwnd_;
  int64_t foreground_process_id_;
  std::optional<int64_t> focus_hwnd_;
  int64_t focus_owner_pid_;
  int64_t probe_mouse_down_;
  int64_t probe_mouse_up_;
  int64_t probe_key_down_;
  bool last_foreground_result_;
  int64_t last_foreground_error_;
  std::unique_ptr<ForegroundGrantSnapshot> foreground_grant_;
  std::string diagnostics_json_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class InputProbeHostApi {
 public:
  InputProbeHostApi(const InputProbeHostApi&) = delete;
  InputProbeHostApi& operator=(const InputProbeHostApi&) = delete;
  virtual ~InputProbeHostApi() {}
  virtual void SampleXInput(std::function<void(ErrorOr<XInputSnapshot> reply)> result) = 0;
  virtual void ExecuteFocus(
    const FocusCommand& command,
    std::function<void(ErrorOr<FocusSnapshot> reply)> result) = 0;
  virtual void Finish(
    const std::string& report_json,
    int64_t exit_code,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;

  // The codec used by InputProbeHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `InputProbeHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    InputProbeHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    InputProbeHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  InputProbeHostApi() = default;
};
}  // namespace mystia_input_probe
#endif  // PIGEON_INPUT_PROBE_API_G_H_
