// Autogenerated from Pigeon (v29.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_WINDOW_API_G_H_
#define PIGEON_WINDOW_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <ostream>
#include <string>

namespace mystia_window_probe {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class WindowProbeHostApi;
  friend class LifecycleHostApi;
  friend class LifecycleFixtureHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class ProbeOperation {
  kInitialize = 0,
  kInspect = 1,
  kArmFrame = 2,
  kPresentFrame = 3,
  kSetInputMode = 4,
  kSetUnderlayColor = 5,
  kClickSample = 6,
  kSendKey = 7,
  kFocusUnderlay = 8,
  kShowInteractive = 9,
  kHide = 10,
  kCloseToHide = 11,
  kSetTopmost = 12,
  kSendF10 = 13,
  kCapture = 14,
  kFinish = 15,
  kRetireCore = 16
};

enum class ProbeInputMode {
  kInteractive = 0,
  kPassThrough = 1
};

enum class LifecycleOperation {
  kStartPrimary = 0,
  kInspect = 1,
  kSecondaryShow = 2,
  kSecondaryToggle = 3,
  kSecondaryExit = 4,
  kSecondaryInvalid = 5,
  kSetPassThrough = 6,
  kHidePrimary = 7,
  kClickTray = 8,
  kOpenTrayMenu = 9,
  kTrayMenuShow = 10,
  kTrayMenuPassthrough = 11,
  kTrayMenuExit = 12,
  kClickPrimary = 13,
  kSendFocusKey = 14,
  kAbort = 15
};

enum class LifecycleControlAction {
  kShow = 0,
  kToggle = 1,
  kExit = 2
};

enum class LifecycleTrayAction {
  kActivate = 0,
  kShow = 1,
  kPassthrough = 2,
  kExit = 3
};


// Generated class from Pigeon that represents data sent in messages.
class ProbeCommand {
 public:
  // Constructs an object setting all fields.
  explicit ProbeCommand(
    const ProbeOperation& operation,
    int64_t revision,
    const ProbeInputMode& input_mode,
    int64_t value,
    double device_pixel_ratio,
    const std::string& text);

  const ProbeOperation& operation() const;
  void set_operation(const ProbeOperation& value_arg);

  int64_t revision() const;
  void set_revision(int64_t value_arg);

  const ProbeInputMode& input_mode() const;
  void set_input_mode(const ProbeInputMode& value_arg);

  int64_t value() const;
  void set_value(int64_t value_arg);

  double device_pixel_ratio() const;
  void set_device_pixel_ratio(double value_arg);

  const std::string& text() const;
  void set_text(std::string_view value_arg);

  bool operator==(const ProbeCommand& other) const;
  bool operator!=(const ProbeCommand& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const ProbeCommand& obj);
 private:
  static ProbeCommand FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class WindowProbeHostApi;
  friend class LifecycleHostApi;
  friend class LifecycleFixtureHostApi;
  friend class PigeonInternalCodecSerializer;
  ProbeOperation operation_;
  int64_t revision_;
  ProbeInputMode input_mode_;
  int64_t value_;
  double device_pixel_ratio_;
  std::string text_;
};


// Generated class from Pigeon that represents data sent in messages.
class ProbeSnapshot {
 public:
  // Constructs an object setting all fields.
  explicit ProbeSnapshot(
    int64_t revision,
    int64_t frame_revision,
    int64_t process_id,
    int64_t top_hwnd,
    int64_t child_hwnd,
    int64_t target_process_id,
    int64_t target_hwnd,
    bool visible,
    const ProbeInputMode& input_mode,
    bool topmost,
    int64_t foreground_hwnd,
    int64_t foreground_process_id,
    int64_t focus_hwnd,
    int64_t flutter_mouse_down,
    int64_t flutter_mouse_up,
    int64_t target_mouse_down,
    int64_t target_mouse_up,
    int64_t flutter_key_down,
    int64_t target_key_down,
    int64_t hotkey_count,
    int64_t dpi,
    double device_pixel_ratio,
    bool top_above_target,
    int64_t sample_hit_hwnd,
    int64_t sample_hit_process_id,
    const ::flutter::EncodableList& pixels,
    const std::string& diagnostics_json);

  int64_t revision() const;
  void set_revision(int64_t value_arg);

  int64_t frame_revision() const;
  void set_frame_revision(int64_t value_arg);

  int64_t process_id() const;
  void set_process_id(int64_t value_arg);

  int64_t top_hwnd() const;
  void set_top_hwnd(int64_t value_arg);

  int64_t child_hwnd() const;
  void set_child_hwnd(int64_t value_arg);

  int64_t target_process_id() const;
  void set_target_process_id(int64_t value_arg);

  int64_t target_hwnd() const;
  void set_target_hwnd(int64_t value_arg);

  bool visible() const;
  void set_visible(bool value_arg);

  const ProbeInputMode& input_mode() const;
  void set_input_mode(const ProbeInputMode& value_arg);

  bool topmost() const;
  void set_topmost(bool value_arg);

  int64_t foreground_hwnd() const;
  void set_foreground_hwnd(int64_t value_arg);

  int64_t foreground_process_id() const;
  void set_foreground_process_id(int64_t value_arg);

  int64_t focus_hwnd() const;
  void set_focus_hwnd(int64_t value_arg);

  int64_t flutter_mouse_down() const;
  void set_flutter_mouse_down(int64_t value_arg);

  int64_t flutter_mouse_up() const;
  void set_flutter_mouse_up(int64_t value_arg);

  int64_t target_mouse_down() const;
  void set_target_mouse_down(int64_t value_arg);

  int64_t target_mouse_up() const;
  void set_target_mouse_up(int64_t value_arg);

  int64_t flutter_key_down() const;
  void set_flutter_key_down(int64_t value_arg);

  int64_t target_key_down() const;
  void set_target_key_down(int64_t value_arg);

  int64_t hotkey_count() const;
  void set_hotkey_count(int64_t value_arg);

  int64_t dpi() const;
  void set_dpi(int64_t value_arg);

  double device_pixel_ratio() const;
  void set_device_pixel_ratio(double value_arg);

  bool top_above_target() const;
  void set_top_above_target(bool value_arg);

  int64_t sample_hit_hwnd() const;
  void set_sample_hit_hwnd(int64_t value_arg);

  int64_t sample_hit_process_id() const;
  void set_sample_hit_process_id(int64_t value_arg);

  const ::flutter::EncodableList& pixels() const;
  void set_pixels(const ::flutter::EncodableList& value_arg);

  const std::string& diagnostics_json() const;
  void set_diagnostics_json(std::string_view value_arg);

  bool operator==(const ProbeSnapshot& other) const;
  bool operator!=(const ProbeSnapshot& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const ProbeSnapshot& obj);
 private:
  static ProbeSnapshot FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class WindowProbeHostApi;
  friend class LifecycleHostApi;
  friend class LifecycleFixtureHostApi;
  friend class PigeonInternalCodecSerializer;
  int64_t revision_;
  int64_t frame_revision_;
  int64_t process_id_;
  int64_t top_hwnd_;
  int64_t child_hwnd_;
  int64_t target_process_id_;
  int64_t target_hwnd_;
  bool visible_;
  ProbeInputMode input_mode_;
  bool topmost_;
  int64_t foreground_hwnd_;
  int64_t foreground_process_id_;
  int64_t focus_hwnd_;
  int64_t flutter_mouse_down_;
  int64_t flutter_mouse_up_;
  int64_t target_mouse_down_;
  int64_t target_mouse_up_;
  int64_t flutter_key_down_;
  int64_t target_key_down_;
  int64_t hotkey_count_;
  int64_t dpi_;
  double device_pixel_ratio_;
  bool top_above_target_;
  int64_t sample_hit_hwnd_;
  int64_t sample_hit_process_id_;
  ::flutter::EncodableList pixels_;
  std::string diagnostics_json_;
};


// Generated class from Pigeon that represents data sent in messages.
class LifecycleCommand {
 public:
  // Constructs an object setting all fields.
  explicit LifecycleCommand(
    const LifecycleOperation& operation,
    int64_t generation);

  const LifecycleOperation& operation() const;
  void set_operation(const LifecycleOperation& value_arg);

  int64_t generation() const;
  void set_generation(int64_t value_arg);

  bool operator==(const LifecycleCommand& other) const;
  bool operator!=(const LifecycleCommand& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const LifecycleCommand& obj);
 private:
  static LifecycleCommand FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class WindowProbeHostApi;
  friend class LifecycleHostApi;
  friend class LifecycleFixtureHostApi;
  friend class PigeonInternalCodecSerializer;
  LifecycleOperation operation_;
  int64_t generation_;
};


// Generated class from Pigeon that represents data sent in messages.
class LifecycleUiEvidence {
 public:
  // Constructs an object setting all fields.
  explicit LifecycleUiEvidence(
    const std::string& git_sha,
    bool ready,
    int64_t pointer_down,
    int64_t key_down,
    bool focused,
    int64_t sequence);

  const std::string& git_sha() const;
  void set_git_sha(std::string_view value_arg);

  bool ready() const;
  void set_ready(bool value_arg);

  int64_t pointer_down() const;
  void set_pointer_down(int64_t value_arg);

  int64_t key_down() const;
  void set_key_down(int64_t value_arg);

  bool focused() const;
  void set_focused(bool value_arg);

  int64_t sequence() const;
  void set_sequence(int64_t value_arg);

  bool operator==(const LifecycleUiEvidence& other) const;
  bool operator!=(const LifecycleUiEvidence& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const LifecycleUiEvidence& obj);
 private:
  static LifecycleUiEvidence FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class WindowProbeHostApi;
  friend class LifecycleHostApi;
  friend class LifecycleFixtureHostApi;
  friend class PigeonInternalCodecSerializer;
  std::string git_sha_;
  bool ready_;
  int64_t pointer_down_;
  int64_t key_down_;
  bool focused_;
  int64_t sequence_;
};


// Generated class from Pigeon that represents data sent in messages.
class LifecycleSnapshot {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit LifecycleSnapshot(
    int64_t generation,
    int64_t observation_sequence,
    int64_t controller_process_id,
    bool primary_alive,
    bool primary_executable_matched,
    int64_t primary_window_count,
    const std::string& native_git_sha,
    const std::string& primary_git_sha,
    int64_t foreground_hwnd,
    int64_t foreground_process_id,
    int64_t mouse_down,
    int64_t mouse_up,
    int64_t key_down,
    bool ui_ready,
    int64_t ui_pointer_down,
    int64_t ui_key_down,
    bool ui_focused,
    int64_t ui_sequence,
    bool tray_added,
    bool tray_versioned,
    bool tray_deleted,
    int64_t tray_callback_count,
    int64_t tray_menu_command_count,
    int64_t port,
    int64_t control_applied,
    int64_t control_rejected,
    int64_t receive_calls,
    int64_t pending_bytes,
    int64_t connection_updates,
    int64_t activations,
    int64_t game_pid,
    bool endpoint_matched,
    bool token_matched,
    int64_t secondary_request_id,
    bool secondary_done,
    int64_t secondary_bind_error,
    int64_t secondary_server_pid,
    int64_t secondary_bytes_sent,
    int64_t secondary_window_count,
    int64_t secondary_error,
    const std::string& diagnostics_json);

  // Constructs an object setting all fields.
  explicit LifecycleSnapshot(
    int64_t generation,
    int64_t observation_sequence,
    int64_t controller_process_id,
    const int64_t* primary_process_id,
    const int64_t* primary_exit_code,
    bool primary_alive,
    bool primary_executable_matched,
    int64_t primary_window_count,
    const std::string& native_git_sha,
    const std::string& primary_git_sha,
    const int64_t* top_hwnd,
    const int64_t* child_hwnd,
    const bool* visible,
    const ProbeInputMode* input_mode,
    int64_t foreground_hwnd,
    int64_t foreground_process_id,
    const int64_t* focus_hwnd,
    int64_t mouse_down,
    int64_t mouse_up,
    int64_t key_down,
    bool ui_ready,
    int64_t ui_pointer_down,
    int64_t ui_key_down,
    bool ui_focused,
    int64_t ui_sequence,
    bool tray_added,
    bool tray_versioned,
    bool tray_deleted,
    int64_t tray_callback_count,
    int64_t tray_menu_command_count,
    const LifecycleTrayAction* tray_last_action,
    int64_t port,
    int64_t control_applied,
    int64_t control_rejected,
    const LifecycleControlAction* control_last_action,
    int64_t receive_calls,
    int64_t pending_bytes,
    int64_t connection_updates,
    int64_t activations,
    int64_t game_pid,
    bool endpoint_matched,
    bool token_matched,
    const int64_t* secondary_pid,
    const LifecycleControlAction* secondary_action,
    int64_t secondary_request_id,
    bool secondary_done,
    const int64_t* secondary_exit_code,
    int64_t secondary_bind_error,
    int64_t secondary_server_pid,
    int64_t secondary_bytes_sent,
    int64_t secondary_window_count,
    int64_t secondary_error,
    const std::string& diagnostics_json);

  int64_t generation() const;
  void set_generation(int64_t value_arg);

  int64_t observation_sequence() const;
  void set_observation_sequence(int64_t value_arg);

  int64_t controller_process_id() const;
  void set_controller_process_id(int64_t value_arg);

  const int64_t* primary_process_id() const;
  void set_primary_process_id(const int64_t* value_arg);
  void set_primary_process_id(int64_t value_arg);

  const int64_t* primary_exit_code() const;
  void set_primary_exit_code(const int64_t* value_arg);
  void set_primary_exit_code(int64_t value_arg);

  bool primary_alive() const;
  void set_primary_alive(bool value_arg);

  bool primary_executable_matched() const;
  void set_primary_executable_matched(bool value_arg);

  int64_t primary_window_count() const;
  void set_primary_window_count(int64_t value_arg);

  const std::string& native_git_sha() const;
  void set_native_git_sha(std::string_view value_arg);

  const std::string& primary_git_sha() const;
  void set_primary_git_sha(std::string_view value_arg);

  const int64_t* top_hwnd() const;
  void set_top_hwnd(const int64_t* value_arg);
  void set_top_hwnd(int64_t value_arg);

  const int64_t* child_hwnd() const;
  void set_child_hwnd(const int64_t* value_arg);
  void set_child_hwnd(int64_t value_arg);

  const bool* visible() const;
  void set_visible(const bool* value_arg);
  void set_visible(bool value_arg);

  const ProbeInputMode* input_mode() const;
  void set_input_mode(const ProbeInputMode* value_arg);
  void set_input_mode(const ProbeInputMode& value_arg);

  int64_t foreground_hwnd() const;
  void set_foreground_hwnd(int64_t value_arg);

  int64_t foreground_process_id() const;
  void set_foreground_process_id(int64_t value_arg);

  const int64_t* focus_hwnd() const;
  void set_focus_hwnd(const int64_t* value_arg);
  void set_focus_hwnd(int64_t value_arg);

  int64_t mouse_down() const;
  void set_mouse_down(int64_t value_arg);

  int64_t mouse_up() const;
  void set_mouse_up(int64_t value_arg);

  int64_t key_down() const;
  void set_key_down(int64_t value_arg);

  bool ui_ready() const;
  void set_ui_ready(bool value_arg);

  int64_t ui_pointer_down() const;
  void set_ui_pointer_down(int64_t value_arg);

  int64_t ui_key_down() const;
  void set_ui_key_down(int64_t value_arg);

  bool ui_focused() const;
  void set_ui_focused(bool value_arg);

  int64_t ui_sequence() const;
  void set_ui_sequence(int64_t value_arg);

  bool tray_added() const;
  void set_tray_added(bool value_arg);

  bool tray_versioned() const;
  void set_tray_versioned(bool value_arg);

  bool tray_deleted() const;
  void set_tray_deleted(bool value_arg);

  int64_t tray_callback_count() const;
  void set_tray_callback_count(int64_t value_arg);

  int64_t tray_menu_command_count() const;
  void set_tray_menu_command_count(int64_t value_arg);

  const LifecycleTrayAction* tray_last_action() const;
  void set_tray_last_action(const LifecycleTrayAction* value_arg);
  void set_tray_last_action(const LifecycleTrayAction& value_arg);

  int64_t port() const;
  void set_port(int64_t value_arg);

  int64_t control_applied() const;
  void set_control_applied(int64_t value_arg);

  int64_t control_rejected() const;
  void set_control_rejected(int64_t value_arg);

  const LifecycleControlAction* control_last_action() const;
  void set_control_last_action(const LifecycleControlAction* value_arg);
  void set_control_last_action(const LifecycleControlAction& value_arg);

  int64_t receive_calls() const;
  void set_receive_calls(int64_t value_arg);

  int64_t pending_bytes() const;
  void set_pending_bytes(int64_t value_arg);

  int64_t connection_updates() const;
  void set_connection_updates(int64_t value_arg);

  int64_t activations() const;
  void set_activations(int64_t value_arg);

  int64_t game_pid() const;
  void set_game_pid(int64_t value_arg);

  bool endpoint_matched() const;
  void set_endpoint_matched(bool value_arg);

  bool token_matched() const;
  void set_token_matched(bool value_arg);

  const int64_t* secondary_pid() const;
  void set_secondary_pid(const int64_t* value_arg);
  void set_secondary_pid(int64_t value_arg);

  const LifecycleControlAction* secondary_action() const;
  void set_secondary_action(const LifecycleControlAction* value_arg);
  void set_secondary_action(const LifecycleControlAction& value_arg);

  int64_t secondary_request_id() const;
  void set_secondary_request_id(int64_t value_arg);

  bool secondary_done() const;
  void set_secondary_done(bool value_arg);

  const int64_t* secondary_exit_code() const;
  void set_secondary_exit_code(const int64_t* value_arg);
  void set_secondary_exit_code(int64_t value_arg);

  int64_t secondary_bind_error() const;
  void set_secondary_bind_error(int64_t value_arg);

  int64_t secondary_server_pid() const;
  void set_secondary_server_pid(int64_t value_arg);

  int64_t secondary_bytes_sent() const;
  void set_secondary_bytes_sent(int64_t value_arg);

  int64_t secondary_window_count() const;
  void set_secondary_window_count(int64_t value_arg);

  int64_t secondary_error() const;
  void set_secondary_error(int64_t value_arg);

  const std::string& diagnostics_json() const;
  void set_diagnostics_json(std::string_view value_arg);

  bool operator==(const LifecycleSnapshot& other) const;
  bool operator!=(const LifecycleSnapshot& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const LifecycleSnapshot& obj);
 private:
  static LifecycleSnapshot FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class WindowProbeHostApi;
  friend class LifecycleHostApi;
  friend class LifecycleFixtureHostApi;
  friend class PigeonInternalCodecSerializer;
  int64_t generation_;
  int64_t observation_sequence_;
  int64_t controller_process_id_;
  std::optional<int64_t> primary_process_id_;
  std::optional<int64_t> primary_exit_code_;
  bool primary_alive_;
  bool primary_executable_matched_;
  int64_t primary_window_count_;
  std::string native_git_sha_;
  std::string primary_git_sha_;
  std::optional<int64_t> top_hwnd_;
  std::optional<int64_t> child_hwnd_;
  std::optional<bool> visible_;
  std::optional<ProbeInputMode> input_mode_;
  int64_t foreground_hwnd_;
  int64_t foreground_process_id_;
  std::optional<int64_t> focus_hwnd_;
  int64_t mouse_down_;
  int64_t mouse_up_;
  int64_t key_down_;
  bool ui_ready_;
  int64_t ui_pointer_down_;
  int64_t ui_key_down_;
  bool ui_focused_;
  int64_t ui_sequence_;
  bool tray_added_;
  bool tray_versioned_;
  bool tray_deleted_;
  int64_t tray_callback_count_;
  int64_t tray_menu_command_count_;
  std::optional<LifecycleTrayAction> tray_last_action_;
  int64_t port_;
  int64_t control_applied_;
  int64_t control_rejected_;
  std::optional<LifecycleControlAction> control_last_action_;
  int64_t receive_calls_;
  int64_t pending_bytes_;
  int64_t connection_updates_;
  int64_t activations_;
  int64_t game_pid_;
  bool endpoint_matched_;
  bool token_matched_;
  std::optional<int64_t> secondary_pid_;
  std::optional<LifecycleControlAction> secondary_action_;
  int64_t secondary_request_id_;
  bool secondary_done_;
  std::optional<int64_t> secondary_exit_code_;
  int64_t secondary_bind_error_;
  int64_t secondary_server_pid_;
  int64_t secondary_bytes_sent_;
  int64_t secondary_window_count_;
  int64_t secondary_error_;
  std::string diagnostics_json_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class WindowProbeHostApi {
 public:
  WindowProbeHostApi(const WindowProbeHostApi&) = delete;
  WindowProbeHostApi& operator=(const WindowProbeHostApi&) = delete;
  virtual ~WindowProbeHostApi() {}
  virtual void Execute(
    const ProbeCommand& command,
    std::function<void(ErrorOr<ProbeSnapshot> reply)> result) = 0;

  // The codec used by WindowProbeHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `WindowProbeHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    WindowProbeHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    WindowProbeHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  WindowProbeHostApi() = default;
};
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class LifecycleHostApi {
 public:
  LifecycleHostApi(const LifecycleHostApi&) = delete;
  LifecycleHostApi& operator=(const LifecycleHostApi&) = delete;
  virtual ~LifecycleHostApi() {}
  virtual void Execute(
    const LifecycleCommand& command,
    std::function<void(ErrorOr<LifecycleSnapshot> reply)> result) = 0;

  // The codec used by LifecycleHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `LifecycleHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    LifecycleHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    LifecycleHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  LifecycleHostApi() = default;
};
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class LifecycleFixtureHostApi {
 public:
  LifecycleFixtureHostApi(const LifecycleFixtureHostApi&) = delete;
  LifecycleFixtureHostApi& operator=(const LifecycleFixtureHostApi&) = delete;
  virtual ~LifecycleFixtureHostApi() {}
  virtual ErrorOr<int64_t> PublishUi(const LifecycleUiEvidence& evidence) = 0;

  // The codec used by LifecycleFixtureHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `LifecycleFixtureHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    LifecycleFixtureHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    LifecycleFixtureHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  LifecycleFixtureHostApi() = default;
};
}  // namespace mystia_window_probe
#endif  // PIGEON_WINDOW_API_G_H_
