export const AUTO_FIRST_ORDER_TICK_MS = 1500;
export const AUTO_NORMAL_ORDER_TICK_MS = 800;
export const AUTOMATION_LEASE_RENEW_INTERVAL_MS = 3000;
export const MAX_SPECIAL_BUSINESS_REJECTED_RECIPE_KEYS = 64;
export const MAX_AUTOMATION_DECISION_DIAGNOSTIC_SIGNATURES = 64;
